packages:
  - 'ember-bem-helpers'
  - 'test-app'
overrides:
  ansi-html: 0.0.9
  babel-plugin-module-resolver: 5.0.3
  cookie: 1.1.1
  package-json: 10.0.1
  tmp: '>=0.2.4'
  diff@<8.0.3: '>=8.0.3'
  serialize-javascript@<=7.0.2: '>=7.0.3'
  '@babel/runtime@<7.26.10': '>=7.26.10'
  uuid@<14.0.0: '>=14.0.0'
autoInstallPeers: false
allowBuilds:
  core-js: false
