allowBuilds:
  core-js: false
  esbuild: false

# Docs: https://pnpm.io/settings
# https://github.com/emberjs/rfcs/pull/907

# we don't want addons to be bad citizens of the ecosystem
autoInstallPeers: false

overrides:
  '@babel/runtime@<7.26.10': ^7.26.10
  brace-expansion@<1.1.16: "<6"
  brace-expansion@>=2.0.0 <2.1.2: ">=2.1.2 <3"
  brace-expansion@>=3.0.0 <5.0.8: ">=5.0.8"
  tmp@<0.2.6: ^0.2.6
  tmp@<=0.2.3: ^0.2.4
  ws@>=8.0.0 <8.20.1: ^8.20.1
  ws@>=8.0.0 <8.21.0: ^8.21.0

# we want true isolation,
# if a dependency is not declared, we want an error
resolvePeersFromWorkspaceRoot: false
