name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 4 * * 2' # every Tuesday at 4am

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 20

permissions:
  contents: read

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v5
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: pnpm
    - name: Install Dependencies
      run: pnpm install --frozen-lockfile
    - name: Lint
      run: pnpm lint
    - name: Run Tests
      run: pnpm test:ember
      working-directory: test-app

  floating:
    name: Floating Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: test

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v5
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: pnpm
    - name: Install Dependencies
      run: pnpm install --no-lockfile
    - name: Run Tests
      run: pnpm test:ember
      working-directory: test-app

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: true
    needs: test

    strategy:
      fail-fast: true
      matrix:
        try-scenario:
          - ember-lts-5.8
          - ember-lts-5.12
          - ember-release
          - ember-beta
          - ember-canary
          - embroider-safe
          - embroider-optimized

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v5
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: pnpm
    - name: Install Dependencies
      run: pnpm install --frozen-lockfile
      working-directory: test-app
    - name: Run Tests
      run: pnpm test:ember-try-one ${{ matrix.try-scenario }}
      working-directory: test-app
